sudo: required

services:
- docker

script:
- docker run --rm -v "$PWD":/data vipintm/xelatex make

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KHvt02yxxi4MAGKZ7lKrF3J/N1wMIRAGuHhR00rubbs3nk+L3/3q/I/viO0t9/rqiSZSYFtra4ishBbARElICC5aBAyxhNxTSCNRACPTZg7NODx4jbrn9zh2cGddU9brlMs5HZaI7h9HvAKAftD+Mwvt+6sHckK8PVB6h4HQEBlelMaJ9Li9OBTtxeOWMo3TT/QU9G2vb+pQZpCv3qFs0IVs/hK6qbMc8m0QSLJTB8KgyZJ0+I4Qk6lxtPntOUYGvJqE4g9BuA4CaGxA5YLcl6sEBt62aOzuc23DfDc1+ty/902/IagXisBhWYI+Lk8NHswIlTNzZHudrrtVlNqd1ZxZ1tMvp3QA7RHaFqrAANWk31We6c7NNJpIHusD+nKs1hTbTgp6dElCLxhlyjPnOGk/kqyPWq5zc7XOcwraxIUvmoQNV1ihHRxylCvoetY0E6HhCcU1PLvt/F3cMYLrSJZoibbWkjD1VBYS15M6h1y1JDA56D+V8Au6GNv8YXmkaHMOsYx7QBCK/7lJm9Rw+72ardsNUbxvDtcsjENNOBm+gPoKAwpcblhVqWUwggeW6Vax6dS2E90PPLeQBbE6oJwN/bDTbLsPLbEW4R12gX2Nxs1pQ/l0Cbc+PkZ13IMv8falQgn29nb5SCkX4385V5ycMSBVrXzSKb1NLmmhfsI=
  file: resume.pdf
  on:
    tags: true
